spring.application.name: board
spring.profiles.active: local

spring:
  config:
    import:
      - db.yml
      - logging.yml
  web:
    resources:
      add-mappings: false

---
spring.config.activate.on-profile: local


jwt:
  secret: rkGU45258GGhiolLO2465TFY5345kGU4525very-secure-secret-key
  expiration: 30m